import Head from "next/head"; 
import Navbar from "../navBar/NavBar";
import Time from "../clock/clock";

const Layout = ({ children }: { children: React.ReactNode }) => (
  <>
    <Head>
      <title>Lizard Interactive Server</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <section>
    <Navbar />
    
    </section>
    <main>{children}</main>
  </>
);

export default Layout;
