import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch } from "react-redux";
import { clearImages } from "../lib/features/images/productImagesSlice";

const Home: React.FC = () => {
  const dispatch = useDispatch();

  const handleClearImages = () => {
    dispatch(clearImages());
  };

  return (
    <>
      <Head>
        <title>Lizard Interactive Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.wrapper}>
            <h1>Welcome to Lizard Interactive Server</h1>
            <button onClick={handleClearImages}>Clear Images</button>
      
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

