"use client";
import { useRef } from "react";
import { useAppSelector, useAppDispatch, useAppStore } from "../lib/hooks";

import Head from "next/head";


export default function Home() {
  
  const count = useAppSelector((state) => state.counter.count);

  return (
    <div>
      <Head>
        <title>Lizard Interactive Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {count}
    </div>
  );
}
