import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Lizard Interactive Server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.wrapper}>
            <h1>Welcome to Lizard Interactive Server</h1>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
